name: Publish to npm

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Publish to npm
      run: npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
